# Generated by Django 3.2.4 on 2022-06-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name='Full Name')),
                ('id_number', models.CharField(max_length=200, unique=True, verbose_name='ID Number')),
                ('email', models.CharField(max_length=200, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, null=True, unique=True, verbose_name='Phone')),
                ('date_of_birth', models.CharField(max_length=200, verbose_name='Date of Birth')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=225)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'supervisor'), (3, 'external_supervisor'), (4, 'coordinator')], default=1)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.department', verbose_name='Department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
