# Generated by Django 3.2.4 on 2022-06-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220616_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
    ]
