# Generated by Django 3.2.4 on 2022-08-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='department',
        ),
    ]
