# Generated by Django 4.1.4 on 2023-01-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'supervisor'), (4, 'coordinator'), (5, 'admin')], default=1),
        ),
    ]
