# Generated by Django 3.2.4 on 2022-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_allocation_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.TextField(max_length=300)),
                ('topic1', models.TextField(max_length=300)),
                ('topic2', models.TextField(max_length=300)),
                ('topic3', models.TextField(max_length=300)),
                ('approval', models.PositiveSmallIntegerField(choices=[(0, 'not_approved'), (1, 'topic1'), (2, 'topic2'), (3, 'topic13')], default=0)),
            ],
        ),
    ]
