# Generated by Django 3.2.4 on 2022-07-18 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='approval',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not_approved'), (1, 'topic_1'), (2, 'topic_2'), (3, 'topic_3')], default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='student',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
