# Generated by Django 3.2.4 on 2022-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20220718_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='approval',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not_approved'), (1, 'topic_1'), (2, 'topic_2'), (3, 'topic_3'), (4, 'rejected')], default=0),
        ),
    ]
