# Generated by Django 3.2.4 on 2022-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20220721_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='message',
            field=models.TextField(blank=True, default=0, max_length=300),
            preserve_default=False,
        ),
    ]
