# Generated by Django 4.1.4 on 2023-01-13 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_grading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter1', models.BooleanField(default=False)),
                ('chapter2', models.BooleanField(default=False)),
                ('chapter3', models.BooleanField(default=False)),
                ('chapter4', models.BooleanField(default=False)),
                ('chapter5', models.BooleanField(default=False)),
                ('student', models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
