# Generated by Django 4.1.4 on 2023-01-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_chapterapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterapproval',
            name='student',
        ),
        migrations.AddField(
            model_name='chapterapproval',
            name='proposal',
            field=models.ForeignKey(default=1, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='project.proposal'),
            preserve_default=False,
        ),
    ]
