# Generated by Django 3.2.4 on 2022-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
