# Generated by Django 4.1.4 on 2023-01-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_session_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
